    import type { DraftStepsConfig } from "../hooks/useDraftEngine";
    
    export const configDraftSteps: Record<number, DraftStepsConfig> = {
        0: [
            { limiteEtape: 9},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 1, indiceToLoad: "FactionBanA", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J1", colorTxtCurrentPlayer: "txtColorPlayerRed", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 2, indiceToLoad: "FactionBanA", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer:"J2", colorTxtCurrentPlayer: "txtColorPlayerBlue", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 1, indiceToLoad: "FactionPickA", txtInstruction: "doit SELECTIONNER sa première faction", txtCurrentPlayer: "J1", colorTxtCurrentPlayer: "txtColorPlayerRed", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 2, indiceToLoad: "FactionPickA", txtInstruction: "doit SELECTIONNER sa première faction", txtCurrentPlayer: "J2", colorTxtCurrentPlayer: "txtColorPlayerBlue", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 2, indiceToLoad: "FactionBanB", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J2", colorTxtCurrentPlayer: "txtColorPlayerBlue", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 1, indiceToLoad: "FactionBanB", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J1", colorTxtCurrentPlayer: "txtColorPlayerRed", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 2, indiceToLoad: "FactionPickB", txtInstruction: "doit SELECTIONNER sa seconde faction", txtCurrentPlayer: "J2", colorTxtCurrentPlayer: "txtColorPlayerBlue", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 1, indiceToLoad: "FactionPickB", txtInstruction: "doit SELECTIONNER sa seconde faction", txtCurrentPlayer: "J1", colorTxtCurrentPlayer: "txtColorPlayerRed", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: true, phase: "Pick"}
        ],

        1: [
            { limiteEtape: 13},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 1, indiceToLoad: "FactionBanA", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J1", colorTxtCurrentPlayer: "txtColorPlayerRed", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 2, indiceToLoad: "FactionBanA", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J2", colorTxtCurrentPlayer: "txtColorPlayerBlue", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 3, indiceToLoad: "FactionBanA", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J3", colorTxtCurrentPlayer: "txtColorPlayerYellow", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 1, indiceToLoad: "FactionPickA", txtInstruction: "doit SELECTIONNER sa première faction", txtCurrentPlayer: "J1", colorTxtCurrentPlayer: "txtColorPlayerRed", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 2, indiceToLoad: "FactionPickA", txtInstruction: "doit SELECTIONNER sa première faction", txtCurrentPlayer: "J2", colorTxtCurrentPlayer: "txtColorPlayerBlue", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 3, indiceToLoad: "FactionPickA", txtInstruction: "doit SELECTIONNER sa première faction", txtCurrentPlayer: "J3", colorTxtCurrentPlayer: "txtColorPlayerYellow", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 3, indiceToLoad: "FactionBanB", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J3", colorTxtCurrentPlayer: "txtColorPlayerYellow", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 2, indiceToLoad: "FactionBanB", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J2", colorTxtCurrentPlayer: "txtColorPlayerBlue", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 1, indiceToLoad: "FactionBanB", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J1", colorTxtCurrentPlayer: "txtColorPlayerRed", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 3, indiceToLoad: "FactionPickB", txtInstruction: "doit SELECTIONNER sa seconde faction", txtCurrentPlayer: "J3", colorTxtCurrentPlayer: "txtColorPlayerYellow", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 2, indiceToLoad: "FactionPickB", txtInstruction: "doit SELECTIONNER sa seconde faction", txtCurrentPlayer: "J2", colorTxtCurrentPlayer: "txtColorPlayerBlue", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 1, indiceToLoad: "FactionPickB", txtInstruction: "doit SELECTIONNER sa seconde faction", txtCurrentPlayer: "J1", colorTxtCurrentPlayer: "txtColorPlayerRed", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: true, phase: "Pick"}
        ],


        2: [
            { limiteEtape: 17},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 1, indiceToLoad: "FactionBanA", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J1", colorTxtCurrentPlayer: "txtColorPlayerRed", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 2, indiceToLoad: "FactionBanA", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J2", colorTxtCurrentPlayer: "txtColorPlayerBlue", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 3, indiceToLoad: "FactionBanA", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J3", colorTxtCurrentPlayer: "txtColorPlayerYellow", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 4, indiceToLoad: "FactionBanA", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J4", colorTxtCurrentPlayer: "txtColorPlayerGreen", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 1, indiceToLoad: "FactionPickA", txtInstruction: "doit SELECTIONNER sa première faction", txtCurrentPlayer: "J1", colorTxtCurrentPlayer: "txtColorPlayerRed", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 2, indiceToLoad: "FactionPickA", txtInstruction: "doit SELECTIONNER sa première faction", txtCurrentPlayer: "J2", colorTxtCurrentPlayer: "txtColorPlayerBlue", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 3, indiceToLoad: "FactionPickA", txtInstruction: "doit SELECTIONNER sa première faction", txtCurrentPlayer: "J3", colorTxtCurrentPlayer: "txtColorPlayerYellow", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 4, indiceToLoad: "FactionPickA", txtInstruction: "doit SELECTIONNER sa première faction", txtCurrentPlayer: "J4", colorTxtCurrentPlayer: "txtColorPlayerGreen", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 4, indiceToLoad: "FactionBanB", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J4", colorTxtCurrentPlayer: "txtColorPlayerGreen", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 3, indiceToLoad: "FactionBanB", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J3", colorTxtCurrentPlayer: "txtColorPlayerYellow", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 2, indiceToLoad: "FactionBanB", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J2", colorTxtCurrentPlayer: "txtColorPlayerBlue", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteRed", idDraftFromCurrentPlayer: 1, indiceToLoad: "FactionBanB", txtInstruction: "doit BANNIR une faction", txtCurrentPlayer: "J1", colorTxtCurrentPlayer: "txtColorPlayerRed", colorTxtCurrentInstructionColor: "txtClignoteRed", etapeFinale: false, phase: "Ban"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 4, indiceToLoad: "FactionPickB", txtInstruction: "doit SELECTIONNER sa seconde faction", txtCurrentPlayer: "J4", colorTxtCurrentPlayer: "txtColorPlayerGreen", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 3, indiceToLoad: "FactionPickB", txtInstruction: "doit SELECTIONNER sa seconde faction", txtCurrentPlayer: "J3", colorTxtCurrentPlayer: "txtColorPlayerYellow", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 2, indiceToLoad: "FactionPickB", txtInstruction: "doit SELECTIONNER sa seconde faction", txtCurrentPlayer: "J2", colorTxtCurrentPlayer: "txtColorPlayerBlue", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: false, phase: "Pick"},
            { txtColor: "txtClignoteGreen", idDraftFromCurrentPlayer: 1, indiceToLoad: "FactionPickB", txtInstruction: "doit SELECTIONNER sa seconde faction", txtCurrentPlayer: "J1", colorTxtCurrentPlayer: "txtColorPlayerRed", colorTxtCurrentInstructionColor: "txtClignoteGreen", etapeFinale: true, phase: "Pick"}
        ]
    }